### ISSUE TITLE
Tags instead of topic

### ISSUE THREAD

**Issue by mr-easy** [benedekrozemberczki/awesome-community-detection#12]
I use your repo a lot, thanks for it!! :)
Just as a suggestion, it will be better to have tags instead of dividing methods by topics. Because we can have several tags in the same paper. 
Tags like overlapping, node-embedding, deep-learning, gcn, tensor-based, nmf, probabilistic, semi-supervised, game-theoretic, survey, metrics, hierarchical, node-attributes, etc.
That would be really helpful I think. I can add the tags to the methods I worked on.
Thanks again for the repo.

**Comment by benedekrozemberczki** [comment]
Hi there,

I am happy to hear that it is useful. Currently I do not really have the capacity to carry out something like this in a consistent manner (meaning every paper). Happy to have contributors to it, but right now I have to focus on other things.

Benedek
