### ISSUE TITLE
can not download the paper code

### ISSUE THREAD

**Issue by xurutingtingting** [benedekrozemberczki/awesome-community-detection#17]
Why I can not download the paper about t-PINE: Tensor-based Predictable Node Embeddings 's matlab reference? Can you update it

**Comment by benedekrozemberczki** [comment]
Because the link is dead and the authors did not republish the code. You can contact them based on the paper.

**Comment by xurutingtingting** [comment]
ok! thank you very much&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Benedek Rozemberczki"<notifications@github.com&gt;; 
发送时间: 2020年6月16日(星期二) 晚上11:19
收件人: "benedekrozemberczki/awesome-community-detection"<awesome-community-detection@noreply.github.com&gt;; 
抄送: "如婷"<781945160@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [benedekrozemberczki/awesome-community-detection] can not download the paper code (#17)





 
Because the link is dead and the authors did not republish the code. You can contact them based on the paper.
