### ISSUE TITLE
Inclusion of other Survey papers that may include

### ISSUE THREAD

**Issue by BradKML** [benedekrozemberczki/awesome-community-detection#19]
Here are some survey papers that lists out Community Detection algorithms
- https://www.semanticscholar.org/paper/Network-Community-Detection-on-Metric-Space-Saha-Ghrera/9487175c52387349da28243e5e78ba56be226b70
- https://www.semanticscholar.org/paper/Improving-Community-Detection-Methods-for-Network-Moradi/48ba86a3d99850181ab7e90b3be0a05ae869330e
- https://www.semanticscholar.org/paper/Various-Approaches-of-Community-Detection-in-A-Mahajan-Kaur/5fdc1fbbd2b758bf654a2d5f68e373ddd3604104
- https://www.semanticscholar.org/paper/Community-Detection-in-Multiplex-Networks-Hanteer-Interdonato/9c2915e1fc26025b6099ab9e9dfac2487692e831
- https://www.semanticscholar.org/paper/Detection-and-analysis-of-overlapping-community-for-Shahriari/013835530c6d8426fd340629f1f3d2ae98d3a860

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR with these?

**Comment by benedekrozemberczki** [comment]
What do you think?

**Comment by BradKML** [comment]
Apologies for not replying, I would do it if there is a field for it.

**Comment by benedekrozemberczki** [comment]
Do you want to create an MD file?
