### ISSUE TITLE
Adding SVI on a-MMSB method by Gopalan and Blei

### ISSUE THREAD

**Issue by mr-easy** [benedekrozemberczki/awesome-community-detection#5]
Efficient discovery of overlapping communities in massive networks (2013) by P Gopalan and David Blei
Paper: https://www.pnas.org/content/110/36/14534
Implementation(by the author): https://github.com/premgopalan/svinet

**Comment by benedekrozemberczki** [comment]
You are welcome to open PR if you want to be a contributor. I can also add
myself.

**Comment by mr-easy** [comment]
okay. created one.
