### ISSUE TITLE
C++ implementation of a paper

### ISSUE THREAD

**Issue by mr-easy** [benedekrozemberczki/awesome-community-detection#6]
Paper: B. Ball, B. Karrer, M.E.J. Newman, "Efficient and principled method for detecting communities in networks", Phys. Rev. E 84 (2011)
C++ implementation by the author: http://www.personal.umich.edu/~mejn/OverlappingLinkCommunities.zip

**Comment by benedekrozemberczki** [comment]
You are welcome to open PR if you want to be a contributor. I can also add
myself.

**Comment by mr-easy** [comment]
okay. created one.
